//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Df {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Df.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you are seeing this message then an error has occured in the algorithm..
        /// </summary>
        internal static string BAD_ALGORITHM {
            get {
                return ResourceManager.GetString("BAD_ALGORITHM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The context has already been added..
        /// </summary>
        internal static string CHECK_ADDED {
            get {
                return ResourceManager.GetString("CHECK_ADDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The column does not belong to this table..
        /// </summary>
        internal static string CHECK_DOES_NOT_BELONG {
            get {
                return ResourceManager.GetString("CHECK_DOES_NOT_BELONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no {0} matching the given {1}..
        /// </summary>
        internal static string CHECK_MATCHING {
            get {
                return ResourceManager.GetString("CHECK_MATCHING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} not found..
        /// </summary>
        internal static string CHECK_NOT_FOUND {
            get {
                return ResourceManager.GetString("CHECK_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value {0} is not a member of an enumerator..
        /// </summary>
        internal static string CHECK_VALUE {
            get {
                return ResourceManager.GetString("CHECK_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} does not implement {1}.
        /// </summary>
        internal static string EX_DOES_NOT_IMPLEMENT {
            get {
                return ResourceManager.GetString("EX_DOES_NOT_IMPLEMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get the constructor arguments on {0}.
        /// </summary>
        internal static string EX_NO_ARGS {
            get {
                return ResourceManager.GetString("EX_NO_ARGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name must be unique..
        /// </summary>
        internal static string EX_NOT_UNIQUE {
            get {
                return ResourceManager.GetString("EX_NOT_UNIQUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please use this function only in LINQ statements..
        /// </summary>
        internal static string EX_ONLY_LINQ {
            get {
                return ResourceManager.GetString("EX_ONLY_LINQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to connect..
        /// </summary>
        internal static string FEEDBACK_FAILED_CONNECTION {
            get {
                return ResourceManager.GetString("FEEDBACK_FAILED_CONNECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good connection..
        /// </summary>
        internal static string FEEDBACK_GOOD_CONNECTION {
            get {
                return ResourceManager.GetString("FEEDBACK_GOOD_CONNECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} failed..
        /// </summary>
        internal static string LOG_ERR_FAILED {
            get {
                return ResourceManager.GetString("LOG_ERR_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get the constructor arguments on {0}.
        /// </summary>
        internal static string LOG_ERR_FAILED_TO_GET_ARGS {
            get {
                return ResourceManager.GetString("LOG_ERR_FAILED_TO_GET_ARGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to read types from assembly {0}.
        /// </summary>
        internal static string LOG_ERR_FAILED_TO_READ_TYPES {
            get {
                return ResourceManager.GetString("LOG_ERR_FAILED_TO_READ_TYPES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} finished..
        /// </summary>
        internal static string LOG_INF_FINISHED {
            get {
                return ResourceManager.GetString("LOG_INF_FINISHED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}({1}) finished..
        /// </summary>
        internal static string LOG_INF_FINISHED_1 {
            get {
                return ResourceManager.GetString("LOG_INF_FINISHED_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type {0} has the attribute {1}..
        /// </summary>
        internal static string LOG_INF_FOUND_ATTRIBUTE {
            get {
                return ResourceManager.GetString("LOG_INF_FOUND_ATTRIBUTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading exported types from {0}.
        /// </summary>
        internal static string LOG_INF_READING_ASSEMBLY {
            get {
                return ResourceManager.GetString("LOG_INF_READING_ASSEMBLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} started..
        /// </summary>
        internal static string LOG_INF_STARTED {
            get {
                return ResourceManager.GetString("LOG_INF_STARTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}({1}) started..
        /// </summary>
        internal static string LOG_INF_STARTED_1 {
            get {
                return ResourceManager.GetString("LOG_INF_STARTED_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has {1} exported types..
        /// </summary>
        internal static string LOG_INF_TYPES_EXPORTED {
            get {
                return ResourceManager.GetString("LOG_INF_TYPES_EXPORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing argument {0}..
        /// </summary>
        internal static string LOG_WRN_MISSING_ARG {
            get {
                return ResourceManager.GetString("LOG_WRN_MISSING_ARG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type {0} does not have a default constructor..
        /// </summary>
        internal static string LOG_WRN_NO_DEFAULT_CONSTRUCTOR {
            get {
                return ResourceManager.GetString("LOG_WRN_NO_DEFAULT_CONSTRUCTOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should not be null..
        /// </summary>
        internal static string LOG_WRN_NULL_ENCOUNTERED {
            get {
                return ResourceManager.GetString("LOG_WRN_NULL_ENCOUNTERED", resourceCulture);
            }
        }
    }
}
