@ECHO OFF

ECHO Cleaning the solution...
dotnet clean -v q code\df.sln > NUL

ECHO Restoring all packages...
dotnet restore -v m code\df.sln > NUL

ECHO Building the solution...
dotnet build -v q code\df.sln > NUL

ECHO Starting all test execution, please wait...
dotnet test -v q code\df.sln
