// --------------------------------------------------------------------------------
// <copyright file="GlobalSuppressions.cs" company="Michalis Sarigiannidis">
// Copyright 2019 © Michalis Sarigiannidis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the solution root for full license information.
// </copyright>
// --------------------------------------------------------------------------------
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "CA1812:Avoid uninstantiated internal classes", Justification = "Dependency Injection.", Scope = "type", Target = "~T:Df.Data.Meta.MetaDbContextFactory")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "CA1812:Avoid uninstantiated internal classes", Justification = "Dependency Injection.", Scope = "type", Target = "~T:Df.Data.SqlFactory")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Redundancy", "RCS1163:Unused parameter.", Justification = "Tell that to EF.", Scope = "type", Target = "~T:Df.Data.Meta.MetaDbContext")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Code Quality", "IDE0069:Disposable fields should be disposed", Justification = "Is too.", Scope = "member", Target = "~F:Df.Data.LocalDbServer._Instance")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Code Quality", "IDE0069:Disposable fields should be disposed", Justification = "Is too.", Scope = "member", Target = "~F:Df.Data.LocalDbServer._SqlLocalDbApi")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Code Quality", "IDE0067:Dispose objects before losing scope", Justification = "Is too.", Scope = "member", Target = "~M:Df.Data.SqlBase.ExecuteQuery``1(System.String,System.Func{System.Data.IDataRecord,``0})~Df.Data.ISqlQueryResultCollection{``0}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Code Quality", "IDE0067:Dispose objects before losing scope", Justification = "Is too.", Scope = "member", Target = "~M:Df.Data.SqlQueryResultCollection`1.GetEnumerator~System.Collections.Generic.IEnumerator{`0}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "CA2213:Disposable fields should be disposed", Justification = "Is too.", Scope = "member", Target = "~F:Df.Data.LocalDbServer._Instance")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "CA2213:Disposable fields should be disposed", Justification = "Is too.", Scope = "member", Target = "~F:Df.Data.LocalDbServer._SqlLocalDbApi")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Security", "CA2100:Review SQL queries for security vulnerabilities", Justification = "Don't care.", Scope = "member", Target = "~M:Df.Data.SqlBase.CreateCommand(System.Data.SqlClient.SqlConnection,System.String)~System.Data.Common.DbCommand")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Security", "CA2100:Review SQL queries for security vulnerabilities", Justification = "Don't care.", Scope = "member", Target = "~M:Df.Data.LocalDbServer.#ctor(System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "Misfire.", Scope = "member", Target = "~M:Df.Data.Meta.MetaDbContext.OnModelCreating(Microsoft.EntityFrameworkCore.ModelBuilder)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "Misfire.", Scope = "member", Target = "~M:Df.Data.Meta.Configurations.ColumnConfiguration.Configure(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder{Df.Data.Meta.Column})")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "Misfire.", Scope = "member", Target = "~M:Df.Data.Meta.Configurations.ForeignKeyColumnConfiguration.Configure(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder{Df.Data.Meta.ForeignKeyColumn})")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "Misfire.", Scope = "member", Target = "~M:Df.Data.Meta.Configurations.ForeignKeyConfiguration.Configure(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder{Df.Data.Meta.ForeignKey})")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "Misfire.", Scope = "member", Target = "~M:Df.Data.Meta.Configurations.IdentityColumnConfiguration.Configure(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder{Df.Data.Meta.IdentityColumn})")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "Misfire.", Scope = "member", Target = "~M:Df.Data.Meta.Configurations.TableConfiguration.Configure(Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder{Df.Data.Meta.Table})")]