CREATE DATABASE [DEMO_DB] ON PRIMARY(NAME= DEMO_DB_DATA, FILENAME = 'D:\data\DEMO_DB.MDF', FILEGROWTH = 512MB) LOG ON (NAME= DEMO_DB_LOG, FILENAME = 'D:\data\DEMO_DB.LDF', FILEGROWTH = 512MB);
GO

USE [DEMO_DB];

CREATE TABLE [dbo].[CATEGORIES](
	[RECID] [bigint] IDENTITY(1,1) PRIMARY KEY NOT NULL,
	[CATEGORY_ORDER] [bigint] NOT NULL,
	[CATEGORY_VALUE] [bigint] NOT NULL,
	[CREATED] [datetime2](7) NOT NULL,
	[MODIFIED] [datetime2](7) NULL,
	[TITLE] [nvarchar](128) NOT NULL,
	[DESCRIPTION] [nvarchar](512) NULL
);

CREATE TABLE [dbo].[ITEMS](
	[RECID] [bigint] IDENTITY(1,1) PRIMARY KEY NOT NULL,
	[CREATED] [datetime2](7) NOT NULL,
	[MODIFIED] [datetime2](7) NULL,
	[NAME] [nvarchar](512) NOT NULL,
	[QUANTITY] [real] NOT NULL,
);

CREATE TABLE [dbo].[ITEM_CATEGORIES](
	[CATEGORY_ID] [bigint] NOT NULL,
	[ITEM_ID] [bigint] NOT NULL,
	[CREATED] [datetime2](7) NOT NULL,
	[MODIFIED] [datetime2](7) NULL,
	 CONSTRAINT [PK_ITEM_CATEGORIES] PRIMARY KEY CLUSTERED 
(
	[CATEGORY_ID] ASC,
	[ITEM_ID] ASC
),
	CONSTRAINT [FK_ITEM_CATEGORIES_CATEGORIES] FOREIGN KEY([CATEGORY_ID]) REFERENCES [dbo].[CATEGORIES] ([RECID]),
	CONSTRAINT [FK_ITEM_CATEGORIES_ITEMS] FOREIGN KEY([ITEM_ID]) REFERENCES [dbo].[ITEMS] ([RECID])
);